### ISSUE TITLE
Slides from December 2019?

### ISSUE THREAD

**Issue by jlucktay** [LondonGophers/admin#48]
Are the slide decks from the three talks at Lush from December available, please? 🙏 

- Zach Jones - A Leisurely Stroll Through the Go Compiler
- Alexander Petrov - Approximate string search in a dictionary
- Roberto Clapis - Practical fuzzing with Go

**Comment by myitcv** [comment]
Thanks for the chaser @jlucktay 

cc @domgreen

**Comment by domgreen** [comment]
Thanks for that @jlucktay have just added a PR to add them into our list of past meetups :D 

Will also add recording once we have uploaded (Christmas and all the merry-ment got the best of us).

**Comment by domgreen** [comment]
Merged to master ... :+1: 

 https://github.com/LondonGophers/admin/tree/master/meetups#december-11-2019---lush
